### PR TITLE
Penambahan foto pelapak pada api produk

### PR DESCRIPTION
**Pull request by masbrodev**
Penyelesaian Issue #173

### CODE REVIEW

**Comment by milhamsuryapratama** [comment]
pindah card di project ke review

**Comment by masbrodev** [comment]
image

Sebenarnya sudah Ada, Namun kemarin masih Null

bisa langsung Update Database & Public di Branch Ini

**Comment by masbrodev** [comment]
https://github.com/commitunuja/mpnj-web/pull/174#issuecomment-608571341

Maksudnya?

**Comment by milhamsuryapratama** [comment]
https://github.com/commitunuja/mpnj-web/projects/1 geser disitu

**Comment by milhamsuryapratama** [comment]
oke, merged.

**Pull request merged**
